### ISSUE TITLE
Silently failing in manjaro linux

### ISSUE THREAD

**Issue by germanp** [nodkz/mongodb-memory-server#107]
Hi,

I'm trying to configure jest to use this package but I've found that doesn't work with manjaro. This is the error I get when I activate the debugging:

```
Determining test suites to run...  Mongo[45603] Starting MongoDB instance with following options: {"port":45603,"dbName":"jest","uri":"mongodb://127.0.0.1:45603/jest","storageEngine":"ephemeralForTest","dbPath":"/tmp/mongo-mem-16705EyirF2mqsJ7s"} +0ms
  Mongo[45603] MongoBinary options: {"downloadDir":"/home/german/Proyectos/dyd/dyd-plus/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"linux","arch":"x64","version":"latest"} +1ms
  Mongo[45603] MongoBinary: Mongod binary path: /home/german/Proyectos/dyd/dyd-plus/node_modules/.cache/mongodb-memory-server/mongodb-binaries/latest/mongod +6ms
  Mongo[45603] MongoBinary: Download lock removed +6ms
  Mongo[45603] STDERR: /home/german/Proyectos/dyd/dyd-plus/node_modules/.cache/mongodb-memory-server/mongodb-binaries/latest/mongod: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/german/Proyectos/dyd/dyd-plus/node_modules/.cache/mongodb-memory-server/mongodb-binaries/latest/mongod)
  Mongo[45603]  +1ms
  Mongo[45603] CLOSE: 1 +0ms
Done in 2.70s.
```

Seems like it is downloading the ubuntu's version which does not work with manjaro, I've tried manually downloading the generic one and it works well. Besides that I think whould be very useful to throw some exception in this case. I checked the code and maybe it can be changed around there https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoInstance.js#L148  to handle an exit codes different than 0, but I'm not realy sure.

Greetings.

**Comment by nodkz** [comment]
Very similar problem was with ubuntu 18 and mongodb v4 https://github.com/nodkz/mongodb-memory-server/issues/89#issuecomment-433169295

Just need determine correct distro for downloading in https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownloadUrl.js

If you have time to make a pull request, please do it. Right now i'm prepearing talk for conference and can look on this problem only in the next month.

Also will be great if you try to play with error reporting in another pull request.

Thanks!

**Comment by AJRdev** [comment]
@germanp What do you mean by downloading from the generic one ? From which mirror link are you downloading the binary for manjaroo ?

**Comment by germanp** [comment]
@AJRdev This one works with manjaro:

http://downloads.mongodb.org/linux/mongodb-linux-x86_64-latest.tgz

The directory tree isn't browseable anymore, but you can check the link here, https://www.mongodb.com/download-center/community, it is the one labeled as 64-bit Legacy

**Comment by AJRdev** [comment]
@germanp Ok thanks for info, so it's pretty weird because that link is the default fallback if the os distrib is not found here : 
https://github.com/nodkz/mongodb-memory-server/blob/master/src/util/MongoBinaryDownloadUrl.js#L116

Where did you saw on your logs that it was downloading the ubuntu version of the mongodb binary ?
t,

**Comment by germanp** [comment]
The actual problem is that [getos](https://github.com/retrohacker/getos) is resolving to ubuntu linux. There are some PRs that should fix that (https://github.com/retrohacker/getos/pull/69 and https://github.com/retrohacker/getos/pull/73), but there weren't merged.

**Comment by AJRdev** [comment]
@germanp Well it's weird since I just tested getos in a Manjaroo environement with docker, and just printed out the result of getos and had : 
```javascript
{ os: 'linux', dist: 'Arch Linux' }
```
It doesn't seem to resolve into ubuntu linux..

**Comment by germanp** [comment]
This is from the node's console:
```
> const getos = require('getos')
undefined
> getos((err, os) => console.log(os))
undefined
> { os: 'linux', dist: 'Ubuntu Linux' }
```

**Comment by AJRdev** [comment]
Ok well I don't really know why it is not returning Ubuntu in the Manjaroo docker image 
```shell
cat /etc/arch-release 
Manjaro Linux
node
> const getos = require('getos')
undefined
> getos((err, os) => console.log(os))
undefined
> { os: 'linux', dist: 'Arch Linux' }
```

Anyway I don't if we can do something since the problem comes from **getos**, and the collaborators don't seem very active on their repo...

**Comment by retrohacker** [comment]
Hi, getos maintainer here, sorry for the radio silence on these PRs. I merged the Manjaro PR today, let me know if this resolves the problem on that distribution.

Taking a look at the arch file now, may do some finagling with that file to make sure we don't accidentally cause other operating systems to regress by reshuffling the order markers appear in that file, we've had that happen in the past.

**Comment by retrohacker** [comment]
Alright, Arch is bumped up in the file and Raspbian appears to still be working: c58eef6b097f105de0957897f8c134df07437b67

Released as 3.1.1

**Comment by AJRdev** [comment]
@retrohacker Awesome thanks ! @germanp Could you give it a try again ?

**Comment by germanp** [comment]
getos is working for me now:

```
> const getos = require("getos")
undefined
> getos
[Function: getOs]
> getos((e, os) => console.log(e, os))
undefined
> null { os: 'linux',
  dist: 'Manjaro Linux',
  codename: 'illyria',
  release: '18.0.0' }
```

**Comment by AJRdev** [comment]
@germanp @nodkz I've created a PR to update the getos package to 3.1.1 to fix this OS detection issue.

**Comment by germanp** [comment]
@AJRdev Yes, I confirm that is working ok now, Thanks for the help!

Maybe next week I can send a PR to improve throwing an error when the command fails.
