### ISSUE TITLE
ReplicaSet throws error while creating: MongoError: not master

### ISSUE THREAD

**Issue by mlewando90** [nodkz/mongodb-memory-server#535]
## Versions

- NodeJS: 14.17.5
- mongodb-memory-server-*: 7.3.6
- mongodb(the binary version): 4.4.4
- system: MacOS

package: mongo-memory-server

## What is the Problem?

When I try to create `MongoMemoryReplSet` I get `MongoError: not master`, but this seems to happen only when I'm running at least two test files in jest.

This is the exact error that I get:
```
    MongoError: not master

      at MessageStream.messageHandler (node_modules/mongodb/lib/cmap/connection.js:268:20)
      at processIncomingData (node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (node_modules/mongodb/lib/cmap/message_stream.js:42:5)
```

### Update 1

Sometimes, there is no error, just timeouts from all tests...

### Update 2

I just received a bit more detailed stacktrace:

```
MongoError: not master
    at MessageStream.messageHandler (/Users/mateuszlewandowski/Projects/konsalnet/konsalnet/scheduling-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:470:12)
    at processIncomingData (/Users/mateuszlewandowski/Projects/konsalnet/konsalnet/scheduling-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/Users/mateuszlewandowski/Projects/konsalnet/konsalnet/scheduling-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:726:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

## Code Example

Setup code
```js
let mongoServer;
export async function setupTestDatabase() {
  mongoServer = await MongoMemoryReplSet.create({ replSet: { count: 3, storageEngine: "wiredTiger" } });
  await mongoServer.waitUntilRunning();
  const mongoUri = mongoServer.getUri();
  await connect(mongoUri, "test-db"); // <- creates mongo client and connects to database, client is then imported in other files
}

export async function tearDownTestDatabase() {
  await disconnect(); // <- disconnects application from mongo
  await mongoServer?.stop();
}
```

and in each test file I have
```js
beforeAll(() => setupTestDatabase());
afterAll(() => tearDownTestDatabase());
```

**Comment by hasezoey** [comment]
in this case `await mongoServer.waitUntilRunning();` should not be needed, because `start` (and by extension `create`) waits until all are running

---

could you provide [Debug Output](https://github.com/nodkz/mongodb-memory-server#enable-debug-mode)?

**Comment by mlewando90** [comment]
I tried without `await mongoServer.waitUntillRunning()` without any lack.

About global setup: in general I have a lot of tests in project that require db connection. I need to have them isolated, which will be hard with global setup (I'll have one instance of DB for all tests). This probably could be addressed with creating some random database on this replica set for each test... but this seems messy... but is it? maybe that would be some way to go? Are there any recommendations for that?

And bout debug output: with debug on I received just timeouts and jest did not close correctly :( here is the output: https://pastebin.com/Lwz6hk5P

**Comment by hasezoey** [comment]
> I need to have them isolated, which will be hard with global setup (I'll have one instance of DB for all tests)

so if i understand correctly, you have a database instance *for every test-suite*?

> This probably could be addressed with creating some random database on this replica set for each test... but this seems messy... but is it?

i would personally recommend using one instance and then multiple databases inside that instance (this should be more resource efficient), MMS does not provide this by default anymore, because mongodb and mongoose URI's are different 

---

also from the log provided, i can tell that starting the database has timed-out in jest (as the hook) and so it seems jest did not call the `afterAll` hook to close the database again

so i would recommend either increasing the timeout, or using `globalSetup` / `globalTeardown`, which to my knowledge does not have a timeout and both should always be called
-> could you provide new debug output once the timeout is increased or moved to `globla*`?

**Comment by hasezoey** [comment]
> process.env.MONGO_URL = mongoUri.slice(0, mongoUri.lastIndexOf("/"));

why do you try to slice out the connection options provided by MMS? (in this case its only `replSet`)

it seems like from documentation (thought i never verified or tried it), is that the option `replSet` is required, otherwise each server in the list is treated as a *standalone server*, which of course the driver may try to write to a secondary

(so it means, without the option the error happening is rather random)

**Comment by mlewando90** [comment]
Yes, the slice out is there directly from documentation, but removing it changes nothing :( I still have `MongoError: not master` when running more than one test case, still only on Mac. 

Interesting thing, is that when I run all tests from the project (~720 test cases) I don't have this error, but there are some random timeouts (~50 tests are failing because of that).

There is one additional "success" though: when I run only one test file and remove this slice from URI, I actually have the reproduction on the minimal example. You can check out current version of https://github.com/mlewando90/mongo-memory-server-replica-set

The reproduction is not always there, but it happens around ech 2 out of 5 runs. Hopefully you will be able to get this on your side.

**Comment by hasezoey** [comment]
> Hopefully you will be able to get this on your side.

if it really is just on Mac, then sorry, but i cannot try any of this - because i do not own any mac

> Interesting thing, is that when I run all tests from the project (~720 test cases) I don't have this error, but there are some random timeouts (~50 tests are failing because of that).

what timeouts? (jest timeouts?), if so, do you know what part of MMS causes this (like what function?)

---

i tried the reproduction repository, but i could not get it to fail, the only change i made was changing the binary version from `4.4.4` to `4.4.6` to not download another version
my system: Linux Mint 20.2 (kernel 5.11.0-27) with NodeJS 16.8.0

**Comment by Uzlopak** [comment]
Probably the computer is to slow. Increase timeouts of yest globally.

**Comment by mlewando90** [comment]
I hope that MacBook Pro on i7+32GB RAM is not too slow for mongo to start in default timeout...

**Comment by hasezoey** [comment]
i did not get a response yet for https://github.com/nodkz/mongodb-memory-server/issues/535#issuecomment-907793148, but a small update: version 8.0.0 released yesterday, which upgraded mongod (driver) and default mongodb binary versions, could you maybe try that?

See [Migrate 8](https://nodkz.github.io/mongodb-memory-server/docs/guides/migration/migrate8)

**Comment by mlewando90** [comment]
I'll test v8.0.0 today and let you know

**Comment by mlewando90** [comment]
I did just a very simple bump of version, and the result is the same, I've still got `MongoError: not master`
I pushed the bump to repo https://github.com/mlewando90/mongo-memory-server-replica-set

**Comment by hasezoey** [comment]
thanks for updating that repository, but i can still not reproduce this problem, it may just be a race condition that i am not aware of, or something macos specific
