### ISSUE TITLE
Feature request: Allow specification of root download URL

### ISSUE THREAD

**Issue by alanshutko** [nodkz/mongodb-memory-server#91]
Our company's build servers do not have direct access to the internet. Instead, they request packages from an internal Artifactory that we host. Currently, MongoBinaryDownloadUrl hardcodes the download for mongodb binaries to fastdl.mongodb.org.

It would be very nice if we could override that with an environment variable to allow us to point this package at a mirror of the mongodb binaries that we could host.  Other packages have a mechanism to do this (e.g. sass_binary_site, chromedriver_cdnurl).

**Comment by AJRdev** [comment]
@alanshutko I find this feature proposal interisting, I've did a fork of the projet and added your feature, could you test it and let met know if it works well for you ? :)

The commit with the new env variable to specify a mirror url for the binary download : 
https://github.com/AJRdev/mongodb-memory-server/commit/5a5ea0984025dbf0335ffdc8e7f0c57c97047bfa

**Comment by nodkz** [comment]
@AJRdev I'm ready to merge your changes! They are perfect! 
Only need to update README.md with new env variable.
Please open PR.

**Comment by AJRdev** [comment]
@nodkz Cool ! PR done and updated the README as well :)

**Comment by nodkz** [comment]
@alanshutko from minute to minute will be published new package version to npm. Please check it.
And if all is ok let us know and close this issue.

**Comment by AJRdev** [comment]
@nodkz Ok thanks ! Is it normal that there is no CI pipeline on the PRs ?

**Comment by nodkz** [comment]
I merged without awaiting CI checks. My miss. 
CI works perfectly ;)

**Comment by AJRdev** [comment]
The CI is still failling on your last commit because of the prettier error :/ 
Maybe we should add a `// prettier-ignore` for this case ?

**Comment by nodkz** [comment]
Fixed. Working from my wife computer. VScode does not catch this error automatically. But after reboot I catch this error. Hate to work from another's machine.

And it's terrible that so many small bugs with this PR.

**Comment by AJRdev** [comment]
@nodkz Yeah eslint can be pretty annoying ! 
What do you think about adding the travis CI in pull requests ?

**Comment by nodkz** [comment]
It has already been added.
I just merge with the master without waiting for the tests. My fault.
So don't worry, nothing to do here. You may look on other PRs, they worked with CI.

**Comment by AJRdev** [comment]
@nodkz Oh allright, my bad.

**Comment by froblesmartin** [comment]
> Our company's build servers do not have direct access to the internet. Instead, they request packages from an internal Artifactory that we host. Currently, MongoBinaryDownloadUrl hardcodes the download for mongodb binaries to fastdl.mongodb.org.
> 
> It would be very nice if we could override that with an environment variable to allow us to point this package at a mirror of the mongodb binaries that we could host. Other packages have a mechanism to do this (e.g. sass_binary_site, chromedriver_cdnurl).

Hi @alanshutko! Could you please share the configuration for the Artifactory mirror? Is it a Generic repository with a custom layout? 

Thank you in advance! :)

**Comment by alanshutko** [comment]
We just put together a generic Artifactory local generic repo, and wrote a script to mirror binaries from https://www.mongodb.org/dl/${platform} and upload there. I don't operate our artifactory, so I don't have more details.

**Comment by froblesmartin** [comment]
> We just put together a generic Artifactory local generic repo, and wrote a script to mirror binaries from [https://www.mongodb.org/dl/${platform}](https://www.mongodb.org/dl/$%7Bplatform%7D) and upload there. I don't operate our artifactory, so I don't have more details.

Okay! Thank you a lot! 😄
